### ISSUE TITLE
Can't locate object method "new" via package "Net::Ping" 

### ISSUE THREAD

**Issue by edi-design** [T0RST3N/fhem-XiaomiSmartHome#10]
Hello together,

since the last update i did two days ago, this module is preventing fhem from starting by printing out the following error message.

Module are installed and it did work before.

```
Can't locate object method "new" via package "Net::Ping" (perhaps you forgot to load "Net::Ping"?) at ./FHEM/71_XiaomiSmartHome.pm line 334, <$fh> line 242.
```

Hopefully someone could help me.

Best regards,
André

**Comment by T0RST3N** [comment]
Hey,

is the package Net::Ping installed?

NET :: PING was also used before the update

greetings
Torte

**Comment by Sequenzial** [comment]
Hi,

I have the same Problem:

`Can't locate object method "new" via package "Net::Ping" (perhaps you forgot to load "Net::Ping"?) at /opt/fhem//FHEM/71_XiaomiSmartHome.pm line 334, <$fh> line 3459.`

Result is that FHEM gets into status exited (means: stop working completely):
___
fhem.service - LSB: FHEM server
   Loaded: loaded (/etc/init.d/fhem; bad; vendor preset: enabled)
   Active: active (**exited**) since Mi 2018-06-06 20:31:12 CEST; 19s ago
     Docs: man:systemd-sysv-generator(8)
  Process: 16832 ExecStop=/etc/init.d/fhem stop (code=exited, status=1/FAILURE)
  Process: 17272 ExecStart=/etc/init.d/fhem start (code=exited, status=0/SUCCESS)

Jun 06 20:31:12 SmartHomeVM systemd[1]: Starting LSB: FHEM server...
Jun 06 20:31:12 SmartHomeVM fhem[17272]: Starting fhem...
Jun 06 20:31:12 SmartHomeVM systemd[1]: Started LSB: FHEM server.
___
When I disable the XiaomiSmartHome Module it runs without problems.

Net:Ping is installed and up-to-date:
___
hajo@SmartHomeVM:/opt/fhem$ sudo cpan install  Net::Ping
Loading internal null logger. Install Log::Log4perl for logging messages
Reading '/home/hajo/.cpan/Metadata'
  Database was generated on Wed, 06 Jun 2018 18:17:03 GMT
CPAN: Module::CoreList loaded ok (v5.20180420)
Net::Ping is up to date (2.66).
___

Any Idea? 
CPAN is v2.18 and I used the upgrade option to upgrade all modules.


Thanks in common!

BR
Hajo
